### PR TITLE
Apply `SpreeMultiVendor` namespace to `*decorator.rb` files

### LINKED ISSUE #146: OrderCommissions are not created when using `spree_gateway` 3.9+
## Context

When used in combination with `spree_gateway` ( https://github.com/spree/spree_gateway )  version 3.9+ , you may encounter the problem that commissions are not created depending on the order in which the modules are loaded.

I'm using spree_multi_vendor and when I updated spree_gateway to 3.8-> 3.9 (October update) I ran into such a problem.

Because `spree_gateway` 3.9.0 introduces `Spree::OrderDecorator` and its method `.prepended` ( https://github.com/spree/spree_gateway/blob/v3.9.0/app/models/spree/order_decorator.rb#L3-L11 ) and `spree_multi_vendor` has already that name class and method ( https://github.com/spree-contrib/spree_multi_vendor/blob/355bd7e18c833b7af2bee18d8b9c0d8d70556c7a/app/models/spree/order_decorator.rb#L2-L6  ) , module name duplication  occurs.

Regarding the order in which the modules are loaded, I don't know how to do it and what kind of problems will occur.
But I can show you a workaround and how to reproduce the problem.

I wrote a Pull Request for a workaround, so take a look( ~TBD~ https://github.com/spree-contrib/spree_multi_vendor/pull/147 ).

## Expected Behavior

OrderCommission are created.

## Actual Behavior

OrderCommission are not created.

## Possible Fix

* PullRequest: ( ~TBD~ https://github.com/spree-contrib/spree_multi_vendor/pull/147 )

Or

* Use `spree_gateway` 3.8-

### Reproducing 1.

1. Install  `spree_gateway` version 3.9.2 (latest version)
2. Install `spree_multi_vendor` latest version.
3. Purchase product which has vendor_id.
4. The order does not have any `order_commissions`.

### Reproducing 2.

In this repo(`spree_multi_vendor`),

* `$ git checkout master`
* `$ rm -rf spec/dummy`
* `$ bundle exec rake test_app`
* Add line `gem 'spree_gateway', '3.9.2'` to `./Gemfile` before `gemspec` line.

```diff
--- a/Gemfile
+++ b/Gemfile
@@ -4,4 +4,6 @@ gem 'spree', github: 'spree/spree', branch: 'master'
 gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: 'master'
 gem 'rails-controller-testing'

+gem 'spree_gateway', '3.9.0'
+
 gemspec
```

* `$ bundle install`
* `$ bundle exec rspec spec/models/spree/order_spec.rb`

```
(..snip..)
Failures:

  1) Spree::Order complete with spree_multi_vendor generates commission records
     Failure/Error:
       expect do
         order.next!
         order.reload
       end.to change { Spree::OrderCommission.count }.by(2).and change { vendor.commissions.count }.by(1)
                                                           .and change { vendor_2.commissions.count }.by(1)

          expected result to have changed by 2, but was changed by 0

       ...and:

             expected result to have changed by 1, but was changed by 0

          ...and:

             expected `vendor_2.commissions.count` to have changed by 1, but was changed by 0

(..snip..)

Finished in 25.37 seconds (files took 6.19 seconds to load)
79 examples, 1 failure

Failed examples:

rspec ./spec/models/spree/order_spec.rb:24 # Spree::Order complete with spree_multi_vendor generates commission records

Randomized with seed 45239

(..snip..)
```

### PR DESCRIPTION
**Pull request by hoshinotsuyoshi**
To avoid module name duplication.

Fix https://github.com/spree-contrib/spree_multi_vendor/issues/146 .

$ git grep -l Decorator | xargs gsed -i -r 's/ Spree::(.+?Decorator\b)/ SpreeMultiVendor::Spree::\1/'

As an example, the mailchimp plugin avoids namespace collision issues in a similar way. ex: https://github.com/spree-contrib/spree_mailchimp_ecommerce/blob/ec776f0a75797667d59ff20a31719d89bc19a51e/app/models/spree_mailchimp_ecommerce/spree/order_decorator.rb#L1-L3

### CODE REVIEW

**Review by damianlegawiec — APPROVED** [review]

**Review by nnande — APPROVED** [review]

File: app/models/spree_multi_vendor/spree/product_property_decorator.rb [hunk 1]
```diff
@@ -11,4 +11,4 @@ def property_name=(name)
   end
 end
 
-Spree::ProductProperty.prepend Spree::ProductPropertyDecorator
\ No newline at end of file
+Spree::ProductProperty.prepend SpreeMultiVendor::Spree::ProductPropertyDecorator
```
Comment (przemosk) [inline app/models/spree_multi_vendor/spree/product_property_decorator.rb]: missing empty line

Comment (hoshinotsuyoshi) [reply app/models/spree_multi_vendor/spree/product_property_decorator.rb]: oh, I'll add it now. Thank you

Comment (hoshinotsuyoshi) [reply app/models/spree_multi_vendor/spree/product_property_decorator.rb]: 919cbba0b19b257a02c116989bc38b266fd848fc
